---
title: "hms_520_TB_Final"
author: "Sophie Whikehart and Ye Htet Naing"
date: "2024-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Final Project - Global Mortality and Risk Factor Contributions for Tuberculosis Estimates from 2015 and 2020

## Abstract

- Ye

- Give an overview of the project, what our goals are and what we hope to find 

## Introduction

- Ye

Provide a brief background: what do we already know about this topic? Why is it interesting? What do you want to add to what already exists?

---

## Data Explanation

## Data Description

For this project we are using the data set from IHME titled: Global Burden of Disease 2021 [GBD 2021] Tuberculosis Estimates 1990-2021 

This data set includes estimates of burden associated with all-form tuberculosis for GBD countries between 1990 and 2021. Tuberculosis mortality was informed by vital registration, verbal autopsy, sample-based vital registration and mortality surveillance data. TB morbidity data includes annual case notifications, data from prevalence surveys, and estimated cause specific mortality [CSMR] of TB among HIV-positive and HIV-negative individuals (IHME GBD 2021).

For our project we are utilizing the `IHME_GBD_2021_TB_MORTALITY_RISK_Y2024M03D19.XLSX` which contains risk deleted deaths due to all-form tuberculosis for alcohol use, smoking, and diabetes and all three risk factors combined by adult age groups by country 

## Methods 

### Data processing 

### Mortality rate change analysis 

### Risk factor contribution analysis 

### Correlation analysis between mortality reduction and risk factors 

---

## Results 

- Ye & Sophie 



